#!/usr/bin/env python3
"""
LVGL image converter -- turn any image into an LVGL C image asset.

Produces a `.c` file with an `lv_img_dsc_t` ready to drop into the firmware
(e.g. halo_ota_demo/firmware/halo_lcd_prod/) and LV_IMG_DECLARE() in your code.

Tuned for THIS project's LVGL config:
  LV_COLOR_DEPTH = 16, LV_COLOR_16_SWAP = 1   (so RGB565 bytes are written hi,lo)

Formats:
  true_color_alpha  3 bytes/px (RGB565 + 8-bit alpha)   -- full colour + transparency [default]
  true_color        2 bytes/px (RGB565, no alpha)       -- opaque images
  alpha_8bit        1 byte/px  (alpha only)             -- mono mask, recoloured at runtime
                                                           via lv_obj_set_style_img_recolor()

Alpha modes (where the transparency comes from):
  source     use the image's own alpha channel            [default]
  white_key  make white -> transparent (good for icons on a white background)
  opaque     fully opaque (alpha = 255 everywhere)

This module is importable (convert_image / write_asset) and runnable as a CLI.
"""
import argparse
import os
import re
import sys

try:
    from PIL import Image
except ImportError:
    sys.stderr.write("This tool needs Pillow:  pip3 install Pillow\n")
    raise

CF = {
    "true_color_alpha": "LV_IMG_CF_TRUE_COLOR_ALPHA",
    "true_color":       "LV_IMG_CF_TRUE_COLOR",
    "alpha_8bit":       "LV_IMG_CF_ALPHA_8BIT",
}
BYTES_PER_PX = {"true_color_alpha": 3, "true_color": 2, "alpha_8bit": 1}


def to565(r, g, b):
    return ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)


def from565(v):
    return (((v >> 11) & 0x1F) << 3, ((v >> 5) & 0x3F) << 2, (v & 0x1F) << 3)


def _parse_hex(c):
    if c is None:
        return None
    c = c.lstrip("#")
    return (int(c[0:2], 16), int(c[2:4], 16), int(c[4:6], 16))


def _resize(im, width, height):
    """width/height: both -> exact; one -> preserve aspect; neither -> unchanged."""
    w0, h0 = im.size
    if width and height:
        return im.resize((width, height), Image.LANCZOS)
    if width and not height:
        return im.resize((width, max(1, round(h0 * width / w0))), Image.LANCZOS)
    if height and not width:
        return im.resize((max(1, round(w0 * height / h0)), height), Image.LANCZOS)
    return im


def convert_image(src, name="my_img", fmt="true_color_alpha",
                  width=None, height=None, crop=False,
                  alpha_mode="source", white_gain=1.4, alpha_threshold=20,
                  recolor=None, swap=True):
    """
    src: path or PIL.Image. Returns (c_source:str, preview:PIL.Image RGBA, meta:dict).
    preview is the image decoded back THROUGH the generated bytes -- i.e. exactly
    what the panel will show (including 565 quantisation and the recolour).
    """
    im = src if isinstance(src, Image.Image) else Image.open(src)
    im = im.convert("RGBA")
    px = im.load()
    W, H = im.size

    # alpha mode -------------------------------------------------------------
    if alpha_mode == "white_key":
        out = Image.new("RGBA", (W, H))
        op = out.load()
        for y in range(H):
            for x in range(W):
                r, g, b, _ = px[x, y]
                a = max(0, min(255, int((255 - min(r, g, b)) * white_gain)))
                op[x, y] = (r, g, b, a)
        im = out
        px = im.load()
    elif alpha_mode == "opaque":
        out = Image.new("RGBA", (W, H))
        op = out.load()
        for y in range(H):
            for x in range(W):
                r, g, b, _ = px[x, y]
                op[x, y] = (r, g, b, 255)
        im = out
        px = im.load()

    # crop to content (alpha) bbox ------------------------------------------
    if crop:
        xs, ys = [], []
        for y in range(im.size[1]):
            for x in range(im.size[0]):
                if px[x, y][3] > alpha_threshold:
                    xs.append(x)
                    ys.append(y)
        if xs and ys:
            im = im.crop((min(xs), min(ys), max(xs) + 1, max(ys) + 1))

    # resize -----------------------------------------------------------------
    im = _resize(im, width, height)
    px = im.load()
    W, H = im.size

    rc = _parse_hex(recolor) if isinstance(recolor, str) else recolor

    # encode -----------------------------------------------------------------
    data = bytearray()
    prev = Image.new("RGBA", (W, H))
    pp = prev.load()
    bg_recolor = rc if rc else (0, 0, 0)  # alpha_8bit preview tint
    for y in range(H):
        for x in range(W):
            r, g, b, a = px[x, y]
            if rc and fmt != "alpha_8bit":
                r, g, b = rc
            if fmt == "alpha_8bit":
                data.append(a)
                tr, tg, tb = bg_recolor
                pp[x, y] = (tr, tg, tb, a)
            else:
                v = to565(r, g, b)
                hi, lo = (v >> 8) & 0xFF, v & 0xFF
                if swap:
                    data += bytes([hi, lo])
                else:
                    data += bytes([lo, hi])
                if fmt == "true_color_alpha":
                    data.append(a)
                qr, qg, qb = from565(v)
                pp[x, y] = (qr, qg, qb, a if fmt == "true_color_alpha" else 255)

    c_src = _emit_c(name, fmt, W, H, data)
    meta = {
        "name": name, "fmt": fmt, "w": W, "h": H,
        "bytes": len(data), "bytes_per_px": BYTES_PER_PX[fmt],
        "swap": swap, "recolor": ("#%02X%02X%02X" % rc) if rc else None,
        "alpha_mode": alpha_mode,
    }
    return c_src, prev, meta


def _emit_c(name, fmt, W, H, data):
    lines = []
    lines.append('#include "lvgl.h"')
    lines.append("#ifndef LV_ATTRIBUTE_MEM_ALIGN")
    lines.append("#define LV_ATTRIBUTE_MEM_ALIGN")
    lines.append("#endif")
    lines.append("")
    lines.append("// %dx%d  %s  %d bytes  (LV_COLOR_16_SWAP=%s)"
                 % (W, H, fmt, len(data), "1"))
    lines.append("const LV_ATTRIBUTE_MEM_ALIGN uint8_t %s_map[] = {" % name)
    for i in range(0, len(data), 16):
        lines.append("  " + ",".join("0x%02x" % b for b in data[i:i + 16]) + ",")
    lines.append("};")
    lines.append("")
    lines.append("const lv_img_dsc_t %s = {" % name)
    lines.append("  .header.cf = %s," % CF[fmt])
    lines.append("  .header.always_zero = 0,")
    lines.append("  .header.reserved = 0,")
    lines.append("  .header.w = %d," % W)
    lines.append("  .header.h = %d," % H)
    lines.append("  .data_size = %d," % len(data))
    lines.append("  .data = %s_map," % name)
    lines.append("};")
    lines.append("")
    return "\n".join(lines)


def decode_preview(c_src, swap=True):
    """Re-decode a generated .c back to an RGBA PIL image (verification)."""
    fmt = next((k for k, v in CF.items() if v in c_src), "true_color_alpha")
    w = int(re.search(r"\.header\.w\s*=\s*(\d+)", c_src).group(1))
    h = int(re.search(r"\.header\.h\s*=\s*(\d+)", c_src).group(1))
    body = re.search(r"_map\[\]\s*=\s*\{(.*?)\};", c_src, re.S).group(1)
    bs = [int(x, 16) for x in re.findall(r"0x[0-9a-fA-F]{2}", body)]
    out = Image.new("RGBA", (w, h))
    op = out.load()
    i = 0
    for y in range(h):
        for x in range(w):
            if fmt == "alpha_8bit":
                op[x, y] = (0, 0, 0, bs[i]); i += 1
            elif fmt == "true_color":
                hi, lo = (bs[i], bs[i+1]) if swap else (bs[i+1], bs[i]); i += 2
                op[x, y] = from565((hi << 8) | lo) + (255,)
            else:
                hi, lo = (bs[i], bs[i+1]) if swap else (bs[i+1], bs[i])
                a = bs[i+2]; i += 3
                op[x, y] = from565((hi << 8) | lo) + (a,)
    return out


def write_asset(out_path, c_src):
    with open(out_path, "w") as f:
        f.write(c_src)
    return out_path


def main():
    ap = argparse.ArgumentParser(description="Convert an image to an LVGL C asset.")
    ap.add_argument("input", help="source image (png/jpg/...)")
    ap.add_argument("-o", "--output", help="output .c path (default: <name>.c)")
    ap.add_argument("-n", "--name", default=None, help="LVGL symbol name (default: from filename)")
    ap.add_argument("-f", "--format", default="true_color_alpha", choices=list(CF.keys()))
    ap.add_argument("--width", type=int)
    ap.add_argument("--height", type=int)
    ap.add_argument("--crop", action="store_true", help="crop to content (alpha) bbox")
    ap.add_argument("--alpha", default="source", choices=["source", "white_key", "opaque"])
    ap.add_argument("--white-gain", type=float, default=1.4)
    ap.add_argument("--recolor", help="force colour RRGGBB (keeps alpha); for alpha_8bit this is the preview tint")
    ap.add_argument("--no-swap", action="store_true", help="disable RGB565 byte-swap (for LV_COLOR_16_SWAP=0)")
    ap.add_argument("--preview", help="also write a decoded PNG preview to this path")
    args = ap.parse_args()

    name = args.name or re.sub(r"[^A-Za-z0-9_]", "_", os.path.splitext(os.path.basename(args.input))[0])
    if name[0].isdigit():
        name = "img_" + name
    c_src, prev, meta = convert_image(
        args.input, name=name, fmt=args.format,
        width=args.width, height=args.height, crop=args.crop,
        alpha_mode=args.alpha, white_gain=args.white_gain,
        recolor=args.recolor, swap=not args.no_swap,
    )
    out = args.output or (name + ".c")
    write_asset(out, c_src)
    if args.preview:
        prev.save(args.preview)
    print("wrote %s  (%dx%d %s, %d bytes flash)" % (out, meta["w"], meta["h"], meta["fmt"], meta["bytes"]))
    print("  -> add `LV_IMG_DECLARE(%s);` and use `lv_img_set_src(img, &%s);`" % (name, name))
    if args.preview:
        print("  preview: %s" % args.preview)


if __name__ == "__main__":
    main()
