// Version.h - SINGLE SOURCE OF TRUTH for Build Metadata
// 
// ⚠️  IMPORTANT: This file is AUTO-GENERATED by tools/generate_version_header.py
// ⚠️  DO NOT EDIT MANUALLY - your changes will be overwritten!
//
// This file defines ALL build metadata used throughout the firmware:
// - FIRMWARE_VERSION: Semantic version (e.g., "0.5.3")
// - BUILD_ID: Unique build identifier (VERSION-DATE-TIME-GIT)
// - BUILD_DATE, BUILD_TIME: Compile-time date/time strings
// - BUILD_GIT_HASH: Git commit hash (or "unknown")
// - FW_EMBED_MARKER: Binary marker string for release verification
//
// All runtime code should use kFirmwareVersion and kBuildId from BuildInfo.h
// (which reference these macros). This ensures consistency across compilation units.
//
// Generated: Sep 04 2026 16:08:12
// Git Hash: 16bd980

#ifndef VERSION_H
#define VERSION_H

#include <Arduino.h>

// Capture which file path the compiler used
#ifndef VERSION_H_PATH
#define VERSION_H_PATH __FILE__
#endif

// Safe mode: if 1, skip OTA + network activity (for debugging boot issues)
#ifndef SAFE_MODE
#define SAFE_MODE 0
#endif

// Firmware version string (semantic versioning: MAJOR.MINOR.PATCH)
#define FIRMWARE_VERSION "6.4.8"

// Build metadata (AUTO-GENERATED - do not override)
#define BUILD_DATE "Sep 04 2026"
#define BUILD_TIME "16:08:12"
#define BUILD_DATE_TIME_STR "Sep 04 2026 16:08:12"
#define BUILD_GIT_HASH "16bd980"

// Build ID: unique identifier for this build (version + date + time + git hash)
// Format: "VERSION-DATE-TIME-GIT" (e.g., "6.4.8-Sep 04 2026-16:08:12-16bd980")
#define BUILD_ID "6.4.8-Sep 04 2026-16:08:12-16bd980"

// Version comparison helper
struct Version {
  int major;
  int minor;
  int patch;
  
  Version() : major(0), minor(0), patch(0) {}
  Version(const char* version_str) {
    parse(version_str);
  }
  
  void parse(const char* version_str) {
    major = minor = patch = 0;
    if (version_str) {
      sscanf(version_str, "%d.%d.%d", &major, &minor, &patch);
    }
  }
  
  bool operator==(const Version& other) const {
    return major == other.major && minor == other.minor && patch == other.patch;
  }
  
  bool operator<(const Version& other) const {
    if (major < other.major) return true;
    if (major > other.major) return false;
    if (minor < other.minor) return true;
    if (minor > other.minor) return false;
    return patch < other.patch;
  }
  
  bool operator>(const Version& other) const {
    return other < *this;
  }
  
  String toString() const {
    char buf[16];
    snprintf(buf, sizeof(buf), "%d.%d.%d", major, minor, patch);
    return String(buf);
  }
};

// Build info structure
struct BuildInfo {
  const char* version;
  const char* build_date;
  const char* build_time;
  const char* git_hash;
  const char* build_id;
  
  BuildInfo() 
    : version(FIRMWARE_VERSION)
    , build_date(BUILD_DATE)
    , build_time(BUILD_TIME)
    , git_hash(BUILD_GIT_HASH)
    , build_id(BUILD_ID) {}
};

// Embed an unmistakable marker in the binary for release verification via `strings`.
// Note: This macro is still used for compile-time stringification.
// Runtime code should use kFwEmbedMarker from BuildInfo.h instead.
#ifndef FW_EMBED_MARKER
#define FW_EMBED_MARKER "HALO_FW_MARKER:6.4.8|BUILD_ID:6.4.8-Sep 04 2026-16:08:12-16bd980|BOARD:sense"
#endif

// Force retention in binary (prevent LTO/GC from stripping it)
// This is kept for backward compatibility, but runtime code should use kFwEmbedMarker
static const char g_fw_embed_marker[] __attribute__((used)) = FW_EMBED_MARKER;

static inline const char* getFwEmbedMarker() {
  return g_fw_embed_marker;
}

#endif // VERSION_H
