// This file was generated by LVGL Image Converter
// Navigation system implementation
// This file uses .cpp extension to enable C++ features like Serial

#ifndef __cplusplus
#error "This file must be compiled as C++ (use .cpp extension)"
#endif

#include <Arduino.h>
#include "navigation.h"
#include "bidi_switch_knob.h"
#include <string.h>

// Knob configuration
#define EXAMPLE_ENCODER_ECA_PIN    8
#define EXAMPLE_ENCODER_ECB_PIN    7

// Screen navigation state
static knob_handle_t s_knob = 0;
static int current_screen_index = 0;
static bool knob_active = false;
static int previous_screen_index = 0;

// Touch debounce
static unsigned long last_touch_time = 0;
static const unsigned long TOUCH_DEBOUNCE_MS = 300;

// Knob sensitivity control
static int knob_left_count = 0;
static int knob_right_count = 0;
static const int KNOB_THRESHOLD = 1;

// Forward declarations
static void stop_delay_timer(void);
static void check_and_start_delay_for_screen(int screen_index);
static void check_and_start_delay_for_screen_by_name(const char* screen_name);
static int find_next_screen_index(int current_idx);
static int find_prev_screen_index(int current_idx);
static int find_current_screen_index(void);

// Screen getter functions
static lv_obj_t* get_Frame_439_1(void) { return ui_Frame_439_1; }
static lv_obj_t* get_Frame_439_2(void) { return ui_Frame_439_2; }
static lv_obj_t* get_Frame_439(void) { return ui_Frame_439; }
static lv_obj_t* get_Frame_440(void) { return ui_Frame_440; }
static lv_obj_t* get_Frame_441_1(void) { return ui_Frame_441_1; }
static lv_obj_t* get_Frame_441(void) { return ui_Frame_441; }
static lv_obj_t* get_Frame_443_1(void) { return ui_Frame_443_1; }
static lv_obj_t* get_Frame_443(void) { return ui_Frame_443; }

// No scroll sequence defined - knob navigation disabled
#define NUM_SCREENS 0
static lv_obj_t* (*screen_objects[])() = { NULL };

// Stub functions for when no scroll sequence is defined
static int find_next_screen_index(int current_idx) {
    (void)current_idx; // Unused parameter
    return -1; // No next screen
}

static int find_prev_screen_index(int current_idx) {
    (void)current_idx; // Unused parameter
    return -1; // No previous screen
}

// Knob callback functions
static void _knob_left_cb(void *arg, void *data) {
  if (!knob_active || !s_knob || NUM_SCREENS == 0) return;
  
  // Sync current screen index before checking
  current_screen_index = find_current_screen_index();
  if (current_screen_index < 0) {
    Serial.println("Current screen is not in scroll sequence - ignoring knob input");
    return; // Current screen is not scrollable
  }
  
  knob_left_count++;
  Serial.printf("Knob left count: %d\n", knob_left_count);
  
  // Only change screen after reaching threshold
  if (knob_left_count >= KNOB_THRESHOLD) {
    knob_left_count = 0; // Reset counter
    knob_right_count = 0; // Reset other direction counter
    
    Serial.println("Knob left - navigating to previous screen");
    
    // Find previous screen (checks for circular connections)
    int prev_idx = find_prev_screen_index(current_screen_index);
    if (prev_idx < 0) {
      Serial.println("No previous screen connection - hard stop");
      return; // Hard stop if no connection
    }
    
    current_screen_index = prev_idx;
    
    // Navigate to the previous screen
    stop_delay_timer(); // Stop any active delay timer
    lv_obj_t* target_screen = screen_objects[current_screen_index]();
    if (target_screen) {
      lv_disp_load_scr(target_screen);
      // Check if this screen has a delay connection
      check_and_start_delay_for_screen(current_screen_index);
    }
  }
}

static void _knob_right_cb(void *arg, void *data) {
  if (!knob_active || !s_knob || NUM_SCREENS == 0) return;
  
  // Sync current screen index before checking
  current_screen_index = find_current_screen_index();
  if (current_screen_index < 0) {
    Serial.println("Current screen is not in scroll sequence - ignoring knob input");
    return; // Current screen is not scrollable
  }
  
  knob_right_count++;
  Serial.printf("Knob right count: %d\n", knob_right_count);
  
  // Only change screen after reaching threshold
  if (knob_right_count >= KNOB_THRESHOLD) {
    knob_right_count = 0; // Reset counter
    knob_left_count = 0; // Reset other direction counter
    
    Serial.println("Knob right - navigating to next screen");
    
    // Find next screen (checks for circular connections)
    int next_idx = find_next_screen_index(current_screen_index);
    if (next_idx < 0) {
      Serial.println("No next screen connection - hard stop");
      return; // Hard stop if no connection
    }
    
    current_screen_index = next_idx;
    
    // Navigate to the next screen
    stop_delay_timer(); // Stop any active delay timer
    lv_obj_t* target_screen = screen_objects[current_screen_index]();
    if (target_screen) {
      lv_disp_load_scr(target_screen);
      // Check if this screen has a delay connection
      check_and_start_delay_for_screen(current_screen_index);
    }
  }
}

static bool touch_debounced(void) {
    unsigned long now = millis();
    if (now - last_touch_time < TOUCH_DEBOUNCE_MS) {
        return false;
    }
    last_touch_time = now;
    return true;
}

// Delay timer state
static unsigned long delay_timer_start = 0;
static unsigned long delay_timer_duration = 0;
static int delay_target_screen_index = -1;
static const char* delay_target_screen_name = NULL;
static bool delay_timer_active = false;

// Start delay timer for screen transition (by index)
static void start_delay_timer(int target_screen_index, unsigned long delay_ms) {
    // Don't restart if already running for the same transition
    if (delay_timer_active && delay_target_screen_index == target_screen_index && delay_timer_duration == delay_ms) {
        Serial.printf("Delay timer already running for screen index %d, skipping restart\n", target_screen_index);
        return;
    }
    delay_timer_start = millis();
    delay_timer_duration = delay_ms;
    delay_target_screen_index = target_screen_index;
    delay_target_screen_name = NULL;
    delay_timer_active = true;
    Serial.printf("Delay timer started: %lu ms to screen index %d\n", delay_ms, target_screen_index);
}

// Start delay timer for screen transition (by name)
static void start_delay_timer_by_name(const char* target_screen_name, unsigned long delay_ms) {
    if (!target_screen_name) return;
    
    // Don't restart if already running for the same transition
    if (delay_timer_active && delay_target_screen_name != NULL && 
        strcmp(delay_target_screen_name, target_screen_name) == 0 && 
        delay_timer_duration == delay_ms) {
        Serial.printf("Delay timer already running for screen %s, skipping restart\n", target_screen_name);
        return;
    }
    delay_timer_start = millis();
    delay_timer_duration = delay_ms;
    delay_target_screen_index = -1;
    delay_target_screen_name = target_screen_name;
    delay_timer_active = true;
    Serial.printf("Delay timer started: %lu ms to screen %s\n", delay_ms, target_screen_name);
}

// Stop delay timer
static void stop_delay_timer(void) {
    delay_timer_active = false;
    delay_target_screen_index = -1;
    delay_target_screen_name = NULL;
    delay_timer_duration = 0;
}

// Check and process delay timer (call this in loop())
void nav_process_delay_timers(void) {
    if (!delay_timer_active) {
        return;
    }
    
    unsigned long now = millis();
    unsigned long elapsed = now - delay_timer_start;
    
    // Debug output every 500ms to verify function is being called
    static unsigned long last_debug = 0;
    if (now - last_debug > 500) {
        last_debug = now;
        Serial.printf("delay_active=%d elapsed=%lu/%lu\n", delay_timer_active, elapsed, delay_timer_duration);
    }
    
    if (elapsed >= delay_timer_duration) {
        Serial.printf("Delay timer EXPIRED! elapsed=%lu >= duration=%lu\n", elapsed, delay_timer_duration);
        
        // Save target info before stopping timer (stop_delay_timer sets them to NULL/-1)
        int target_index = delay_target_screen_index;
        const char* target_name = delay_target_screen_name;
        
        stop_delay_timer();
        
        // Navigate to target screen
        if (target_index >= 0 && target_index < NUM_SCREENS) {
            // Navigate by index (when scroll sequence exists)
            Serial.printf("Delay timer expired, transitioning to screen index %d\n", target_index);
            current_screen_index = target_index;
            lv_obj_t* target_screen = screen_objects[target_index]();
            if (target_screen) {
                lv_disp_load_scr(target_screen);
                // Check if the new screen has a delay connection
                check_and_start_delay_for_screen(target_index);
            } else {
                Serial.printf("ERROR: target_screen is NULL for index %d\n", target_index);
            }
        } else if (target_name != NULL) {
            // Navigate by name (when no scroll sequence)
            Serial.printf("Delay timer expired, transitioning to screen %s\n", target_name);
            // Use no-debounce version for programmatic navigation
            nav_navigate_to_screen_no_debounce(target_name);
            // Check if the new screen has a delay connection (by name)
            check_and_start_delay_for_screen_by_name(target_name);
        } else {
            Serial.println("ERROR: Delay timer expired but no valid target (both index and name are invalid)");
        }
    }
}

// Check if current screen has delay connection and start timer (by name, for when no scroll sequence)
static void check_and_start_delay_for_screen_by_name(const char* screen_name) {
    if (!screen_name) {
        Serial.println("check_and_start_delay_for_screen_by_name: screen_name is NULL");
        return;
    }
    
    Serial.printf("check_and_start_delay_for_screen_by_name: checking screen %s\n", screen_name);
    
    // Find delay connection from this screen
    Serial.println("No delay connections defined");
}

// Check if current screen has delay connection and start timer (by index, for when scroll sequence exists)
static void check_and_start_delay_for_screen(int screen_index) {
    if (NUM_SCREENS == 0) {
        // No scroll sequence, use name-based lookup instead
        Serial.println("check_and_start_delay_for_screen: NUM_SCREENS == 0, skipping");
        return;
    }
    if (screen_index < 0 || screen_index >= NUM_SCREENS) {
        Serial.printf("check_and_start_delay_for_screen: invalid index %d\n", screen_index);
        return;
    }
    
    Serial.printf("check_and_start_delay_for_screen: checking screen index %d\n", screen_index);
    
    // Find delay connection from this screen
    Serial.println("No delay connections defined or no scroll sequence");
}

// Public wrapper functions for delay checking (called from ui_init)
void nav_check_delay_for_screen_by_name(const char* screen_name) {
    check_and_start_delay_for_screen_by_name(screen_name);
}

void nav_check_delay_for_screen(int screen_index) {
    check_and_start_delay_for_screen(screen_index);
}

// Helper function to find current screen index based on displayed screen
static int find_current_screen_index(void) {
  if (NUM_SCREENS == 0) return -1; // No scroll sequence
  lv_obj_t* current_screen = lv_scr_act();
  for (int i = 0; i < NUM_SCREENS; i++) {
    lv_obj_t* screen = screen_objects[i]();
    if (screen == current_screen) {
      return i;
    }
  }
  return -1; // Current screen is not in scroll sequence - return invalid index
}

// Function to activate knob control
void nav_activate_knob(void) {
  knob_active = true;
  knob_left_count = 0; // Reset counters
  knob_right_count = 0;
  
  // Register knob callbacks
  if (s_knob) {
    iot_knob_register_cb(s_knob, KNOB_LEFT, _knob_left_cb, NULL);
    iot_knob_register_cb(s_knob, KNOB_RIGHT, _knob_right_cb, NULL);
  }
  Serial.println("Knob navigation activated");
}

// Function to deactivate knob control
void nav_deactivate_knob(void) {
  knob_active = false;
  knob_left_count = 0; // Reset counters
  knob_right_count = 0;
  
  // Unregister knob callbacks when inactive
  if (s_knob) {
    iot_knob_unregister_cb(s_knob, KNOB_LEFT);
    iot_knob_unregister_cb(s_knob, KNOB_RIGHT);
  }
  Serial.println("Knob navigation deactivated");
}

void nav_init(void) {
    // Only initialize knob navigation if scroll sequence is defined
    if (NUM_SCREENS == 0) {
        Serial.println("No scroll sequence defined - knob navigation disabled");
        // Still check for delay connections on initial screen by name
        lv_obj_t* current_screen = lv_scr_act();
        // Try to find current screen name by checking all screens
        if (current_screen == ui_Frame_439_1) {
            nav_check_delay_for_screen_by_name("Frame_439_1");
            return;
        }
        if (current_screen == ui_Frame_439_2) {
            nav_check_delay_for_screen_by_name("Frame_439_2");
            return;
        }
        if (current_screen == ui_Frame_439) {
            nav_check_delay_for_screen_by_name("Frame_439");
            return;
        }
        if (current_screen == ui_Frame_440) {
            nav_check_delay_for_screen_by_name("Frame_440");
            return;
        }
        if (current_screen == ui_Frame_441_1) {
            nav_check_delay_for_screen_by_name("Frame_441_1");
            return;
        }
        if (current_screen == ui_Frame_441) {
            nav_check_delay_for_screen_by_name("Frame_441");
            return;
        }
        if (current_screen == ui_Frame_443_1) {
            nav_check_delay_for_screen_by_name("Frame_443_1");
            return;
        }
        if (current_screen == ui_Frame_443) {
            nav_check_delay_for_screen_by_name("Frame_443");
            return;
        }
        return;
    }
    
    // Sync current screen index with actually displayed screen
    current_screen_index = find_current_screen_index();
    
    // Initialize knob
    knob_config_t cfg = {
        .gpio_encoder_a = EXAMPLE_ENCODER_ECA_PIN,
        .gpio_encoder_b = EXAMPLE_ENCODER_ECB_PIN,
    };
    
    s_knob = iot_knob_create(&cfg);
    if (s_knob) {
        Serial.println("Knob initialized successfully");
        nav_activate_knob();
    } else {
        Serial.println("Failed to initialize knob");
    }
    
    // Check if initial screen has a delay connection
    // Use index-based if we have a scroll sequence, otherwise use name-based
    if (NUM_SCREENS > 0) {
        check_and_start_delay_for_screen(current_screen_index);
    } else {
        // No scroll sequence, find current screen by name and check delay
        lv_obj_t* current_screen = lv_scr_act();
        if (current_screen == ui_Frame_439_1) {
            nav_check_delay_for_screen_by_name("Frame_439_1");
            return;
        }
        if (current_screen == ui_Frame_439_2) {
            nav_check_delay_for_screen_by_name("Frame_439_2");
            return;
        }
        if (current_screen == ui_Frame_439) {
            nav_check_delay_for_screen_by_name("Frame_439");
            return;
        }
        if (current_screen == ui_Frame_440) {
            nav_check_delay_for_screen_by_name("Frame_440");
            return;
        }
        if (current_screen == ui_Frame_441_1) {
            nav_check_delay_for_screen_by_name("Frame_441_1");
            return;
        }
        if (current_screen == ui_Frame_441) {
            nav_check_delay_for_screen_by_name("Frame_441");
            return;
        }
        if (current_screen == ui_Frame_443_1) {
            nav_check_delay_for_screen_by_name("Frame_443_1");
            return;
        }
        if (current_screen == ui_Frame_443) {
            nav_check_delay_for_screen_by_name("Frame_443");
            return;
        }
    }
}

void nav_go_to_index(int index) {
    if (index >= 0 && index < NUM_SCREENS) {
        stop_delay_timer(); // Stop any active delay timer
        current_screen_index = index;
        lv_obj_t *scr = screen_objects[index]();
        if (scr) {
            lv_disp_load_scr(scr);
            // Check if this screen has a delay connection
            check_and_start_delay_for_screen(index);
        }
    }
}

void nav_navigate_to_screen(const char* screen_name) {
    if (!touch_debounced()) return;
    
    // Find screen by name
    if (strcmp(screen_name, "Frame_439_1") == 0) {
        // Screen not in scroll sequence, navigating directly
        stop_delay_timer(); // Stop any active delay timer
        lv_obj_t *scr = get_Frame_439_1();
        if (scr) {
            lv_disp_load_scr(scr);
            // Check if this screen has a delay connection
            check_and_start_delay_for_screen_by_name("Frame_439_1");
        }
        return;
    }
    if (strcmp(screen_name, "Frame_439_2") == 0) {
        // Screen not in scroll sequence, navigating directly
        stop_delay_timer(); // Stop any active delay timer
        lv_obj_t *scr = get_Frame_439_2();
        if (scr) {
            lv_disp_load_scr(scr);
            // Check if this screen has a delay connection
            check_and_start_delay_for_screen_by_name("Frame_439_2");
        }
        return;
    }
    if (strcmp(screen_name, "Frame_439") == 0) {
        // Screen not in scroll sequence, navigating directly
        stop_delay_timer(); // Stop any active delay timer
        lv_obj_t *scr = get_Frame_439();
        if (scr) {
            lv_disp_load_scr(scr);
            // Check if this screen has a delay connection
            check_and_start_delay_for_screen_by_name("Frame_439");
        }
        return;
    }
    if (strcmp(screen_name, "Frame_440") == 0) {
        // Screen not in scroll sequence, navigating directly
        stop_delay_timer(); // Stop any active delay timer
        lv_obj_t *scr = get_Frame_440();
        if (scr) {
            lv_disp_load_scr(scr);
            // Check if this screen has a delay connection
            check_and_start_delay_for_screen_by_name("Frame_440");
        }
        return;
    }
    if (strcmp(screen_name, "Frame_441_1") == 0) {
        // Screen not in scroll sequence, navigating directly
        stop_delay_timer(); // Stop any active delay timer
        lv_obj_t *scr = get_Frame_441_1();
        if (scr) {
            lv_disp_load_scr(scr);
            // Check if this screen has a delay connection
            check_and_start_delay_for_screen_by_name("Frame_441_1");
        }
        return;
    }
    if (strcmp(screen_name, "Frame_441") == 0) {
        // Screen not in scroll sequence, navigating directly
        stop_delay_timer(); // Stop any active delay timer
        lv_obj_t *scr = get_Frame_441();
        if (scr) {
            lv_disp_load_scr(scr);
            // Check if this screen has a delay connection
            check_and_start_delay_for_screen_by_name("Frame_441");
        }
        return;
    }
    if (strcmp(screen_name, "Frame_443_1") == 0) {
        // Screen not in scroll sequence, navigating directly
        stop_delay_timer(); // Stop any active delay timer
        lv_obj_t *scr = get_Frame_443_1();
        if (scr) {
            lv_disp_load_scr(scr);
            // Check if this screen has a delay connection
            check_and_start_delay_for_screen_by_name("Frame_443_1");
        }
        return;
    }
    if (strcmp(screen_name, "Frame_443") == 0) {
        // Screen not in scroll sequence, navigating directly
        stop_delay_timer(); // Stop any active delay timer
        lv_obj_t *scr = get_Frame_443();
        if (scr) {
            lv_disp_load_scr(scr);
            // Check if this screen has a delay connection
            check_and_start_delay_for_screen_by_name("Frame_443");
        }
        return;
    }
}

// Navigate to screen without debounce (for programmatic navigation like delay timers)
void nav_navigate_to_screen_no_debounce(const char* screen_name) {
    if (!screen_name) return;
    
    // Find screen by name
    if (strcmp(screen_name, "Frame_439_1") == 0) {
        // Screen not in scroll sequence, navigating directly
        stop_delay_timer(); // Stop any active delay timer
        lv_obj_t *scr = get_Frame_439_1();
        if (scr) {
            lv_disp_load_scr(scr);
            // Check if this screen has a delay connection
            check_and_start_delay_for_screen_by_name("Frame_439_1");
        }
        return;
    }
    if (strcmp(screen_name, "Frame_439_2") == 0) {
        // Screen not in scroll sequence, navigating directly
        stop_delay_timer(); // Stop any active delay timer
        lv_obj_t *scr = get_Frame_439_2();
        if (scr) {
            lv_disp_load_scr(scr);
            // Check if this screen has a delay connection
            check_and_start_delay_for_screen_by_name("Frame_439_2");
        }
        return;
    }
    if (strcmp(screen_name, "Frame_439") == 0) {
        // Screen not in scroll sequence, navigating directly
        stop_delay_timer(); // Stop any active delay timer
        lv_obj_t *scr = get_Frame_439();
        if (scr) {
            lv_disp_load_scr(scr);
            // Check if this screen has a delay connection
            check_and_start_delay_for_screen_by_name("Frame_439");
        }
        return;
    }
    if (strcmp(screen_name, "Frame_440") == 0) {
        // Screen not in scroll sequence, navigating directly
        stop_delay_timer(); // Stop any active delay timer
        lv_obj_t *scr = get_Frame_440();
        if (scr) {
            lv_disp_load_scr(scr);
            // Check if this screen has a delay connection
            check_and_start_delay_for_screen_by_name("Frame_440");
        }
        return;
    }
    if (strcmp(screen_name, "Frame_441_1") == 0) {
        // Screen not in scroll sequence, navigating directly
        stop_delay_timer(); // Stop any active delay timer
        lv_obj_t *scr = get_Frame_441_1();
        if (scr) {
            lv_disp_load_scr(scr);
            // Check if this screen has a delay connection
            check_and_start_delay_for_screen_by_name("Frame_441_1");
        }
        return;
    }
    if (strcmp(screen_name, "Frame_441") == 0) {
        // Screen not in scroll sequence, navigating directly
        stop_delay_timer(); // Stop any active delay timer
        lv_obj_t *scr = get_Frame_441();
        if (scr) {
            lv_disp_load_scr(scr);
            // Check if this screen has a delay connection
            check_and_start_delay_for_screen_by_name("Frame_441");
        }
        return;
    }
    if (strcmp(screen_name, "Frame_443_1") == 0) {
        // Screen not in scroll sequence, navigating directly
        stop_delay_timer(); // Stop any active delay timer
        lv_obj_t *scr = get_Frame_443_1();
        if (scr) {
            lv_disp_load_scr(scr);
            // Check if this screen has a delay connection
            check_and_start_delay_for_screen_by_name("Frame_443_1");
        }
        return;
    }
    if (strcmp(screen_name, "Frame_443") == 0) {
        // Screen not in scroll sequence, navigating directly
        stop_delay_timer(); // Stop any active delay timer
        lv_obj_t *scr = get_Frame_443();
        if (scr) {
            lv_disp_load_scr(scr);
            // Check if this screen has a delay connection
            check_and_start_delay_for_screen_by_name("Frame_443");
        }
        return;
    }
}

int nav_find_current_index(void) {
    return find_current_screen_index();
}
