// This file was generated by LVGL Image Converter
// Navigation system for scroll and touch

#ifndef NAVIGATION_H
#define NAVIGATION_H

#include "lvgl.h"
#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

void nav_init(void);
void nav_activate_knob(void);
void nav_deactivate_knob(void);
void nav_go_to_index(int index);
void nav_navigate_to_screen(const char* screen_name);
void nav_navigate_to_screen_no_debounce(const char* screen_name);
int nav_find_current_index(void);
void nav_process_delay_timers(void);
void nav_check_delay_for_screen_by_name(const char* screen_name);
void nav_check_delay_for_screen(int screen_index);

#ifdef __cplusplus
}
#endif

#endif
