// This file was generated by LVGL Image Converter
// LVGL version: 8.3.6

#include "ui.h"

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t *dispp = lv_disp_get_default();
    lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    
    // Initialize all screens
    ui_Frame_439_1_screen_init();
    ui_Frame_439_2_screen_init();
    ui_Frame_439_screen_init();
    ui_Frame_440_screen_init();
    ui_Frame_441_1_screen_init();
    ui_Frame_441_screen_init();
    ui_Frame_443_1_screen_init();
    ui_Frame_443_screen_init();

    // Load initial screen (first screen in storyboard order)
    lv_disp_load_scr(ui_Frame_439_1);
}

void ui_destroy(void)
{
    ui_Frame_439_1_screen_destroy();
    ui_Frame_439_2_screen_destroy();
    ui_Frame_439_screen_destroy();
    ui_Frame_440_screen_destroy();
    ui_Frame_441_1_screen_destroy();
    ui_Frame_441_screen_destroy();
    ui_Frame_443_1_screen_destroy();
    ui_Frame_443_screen_destroy();
}
