// This file was generated by LVGL Image Converter
// LVGL version: 8.3.6

#ifndef _UI_H
#define _UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
#include "navigation.h"

///////////////////// SCREENS ////////////////////
#include "ui_Frame_439_1.h"
#include "ui_Frame_439_2.h"
#include "ui_Frame_439.h"
#include "ui_Frame_440.h"
#include "ui_Frame_441_1.h"
#include "ui_Frame_441.h"
#include "ui_Frame_443_1.h"
#include "ui_Frame_443.h"

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_Frame_439_1_png);
LV_IMG_DECLARE(ui_img_Frame_439_2_png);
LV_IMG_DECLARE(ui_img_Frame_439_png);
LV_IMG_DECLARE(ui_img_Frame_440_png);
LV_IMG_DECLARE(ui_img_Frame_441_1_png);
LV_IMG_DECLARE(ui_img_Frame_441_png);
LV_IMG_DECLARE(ui_img_Frame_443_1_png);
LV_IMG_DECLARE(ui_img_Frame_443_png);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
