// This file was generated by LVGL Image Converter
// LVGL version: 8.3.6

#ifndef UI_FRAME_441_1_H
#define UI_FRAME_441_1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Frame_441_1
extern void ui_Frame_441_1_screen_init(void);
extern void ui_Frame_441_1_screen_destroy(void);
extern lv_obj_t *ui_Frame_441_1;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
