// This file was generated by LVGL Image Converter
// LVGL version: 8.3.6

#ifndef UI_FRAME_440_H
#define UI_FRAME_440_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Frame_440
extern void ui_Frame_440_screen_init(void);
extern void ui_Frame_440_screen_destroy(void);
extern lv_obj_t *ui_Frame_440;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
