// This file was generated by LVGL Image Converter
// LVGL version: 8.3.6

#include "ui.h"

lv_obj_t *ui_Frame_441_1 = NULL;

void ui_Frame_441_1_screen_init(void)
{
    ui_Frame_441_1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Frame_441_1, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_img_src(ui_Frame_441_1, &ui_img_Frame_441_1_png, LV_PART_MAIN | LV_STATE_DEFAULT);
}

void ui_Frame_441_1_screen_destroy(void)
{
    if (ui_Frame_441_1) lv_obj_del(ui_Frame_441_1);
    ui_Frame_441_1 = NULL;
}
