// This file was generated by LVGL Image Converter
// LVGL version: 8.3.6

#ifndef UI_FRAME_439_2_H
#define UI_FRAME_439_2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Frame_439_2
extern void ui_Frame_439_2_screen_init(void);
extern void ui_Frame_439_2_screen_destroy(void);
extern lv_obj_t *ui_Frame_439_2;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
