// This file was generated by LVGL Image Converter
// LVGL version: 8.3.6

#ifndef _UI_HELPERS_H
#define _UI_HELPERS_H

#ifdef __cplusplus
extern "C" {
#endif

#include "ui.h"

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
