#!/usr/bin/env python3
"""Bake the approved right-rim cue into an LVGL alpha mask (no runtime rotation).

Pass the design's Nunito-Black.ttf with --font. The generated header records its
hash; normal firmware builds consume the checked-in header, not Pillow/fonts.
"""
import argparse
import hashlib
import math
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--font', type=Path, required=True)
    parser.add_argument('--out-header', type=Path, required=True)
    parser.add_argument('--preview', type=Path, required=True)
    args = parser.parse_args()
    scale = 4
    mask = Image.new('L', (360 * scale, 360 * scale), 0)
    font = ImageFont.truetype(str(args.font), 16 * scale)
    text, radius = 'Scroll for next step', 148
    widths = [font.getlength(c) / scale + .2 for c in text]
    span = sum(widths) / radius * 180 / math.pi
    angle = 90 - span / 2

    def point(degrees, r):
        a = math.radians(degrees)
        return ((180 + r * math.sin(a)) * scale,
                (180 - r * math.cos(a)) * scale)

    for c, width in zip(text, widths):
        half = width / radius * 180 / math.pi / 2
        angle += half
        glyph = Image.new('L', (32 * scale, 32 * scale), 0)
        ImageDraw.Draw(glyph).text((16 * scale, 16 * scale), c, font=font,
                                  anchor='mm', fill=255)
        glyph = glyph.rotate(-angle, resample=Image.Resampling.BICUBIC)
        x, y = point(angle, radius)
        mask.paste(glyph, (round(x - 16 * scale), round(y - 16 * scale)), glyph)
        angle += half
    draw = ImageDraw.Draw(mask)
    hi = 90 + span / 2 + 7
    for begin, end in ((hi, hi + 17),):
        pts = [point(begin + (end - begin) * i / 80, 168) for i in range(81)]
        draw.line(pts, fill=255, width=2 * scale, joint='curve')
    for a, direction in ((hi + 17, 1),):
        tip = point(a, 168)
        tail = point(a - direction * 2.8, 168)
        radial = (math.sin(math.radians(a)), -math.cos(math.radians(a)))
        wings = [(tail[0] + s * 3.4 * scale * radial[0],
                  tail[1] + s * 3.4 * scale * radial[1]) for s in (-1, 1)]
        draw.line([wings[0], tip, wings[1]], fill=255, width=2 * scale, joint='curve')
    mask = mask.resize((360, 360), Image.Resampling.LANCZOS)
    mask = mask.point(lambda a: a if a >= 8 else 0)
    box = mask.getbbox()
    assert box and box[0] > 270 and box[2] < 355
    cropped = mask.crop(box)
    width, height = cropped.size
    data = cropped.tobytes()
    rows = ['  ' + ','.join(f'0x{x:02x}' for x in data[i:i + 24]) + ','
            for i in range(0, len(data), 24)]
    font_hash = hashlib.sha256(args.font.read_bytes()).hexdigest()
    header = f'''// Generated by LCD_Minimal/generate_provision_scroll_cue.py; do not hand edit.
// Nunito-Black.ttf SHA256: {font_hash}
#ifndef LCD_PROVISION_SCROLL_ASSET_H
#define LCD_PROVISION_SCROLL_ASSET_H
static const int PROVISION_SCROLL_CUE_X = {box[0]};
static const int PROVISION_SCROLL_CUE_Y = {box[1]};
static const uint8_t provision_scroll_cue_map[] = {{
{chr(10).join(rows)}
}};
static const lv_img_dsc_t provision_scroll_cue_img = {{
  {{LV_IMG_CF_ALPHA_8BIT, 0, 0, {width}, {height}}},
  sizeof(provision_scroll_cue_map), provision_scroll_cue_map
}};
#endif
'''
    args.out_header.parent.mkdir(parents=True, exist_ok=True)
    args.out_header.write_text(header)
    preview = Image.new('RGB', (360, 360), '#f5e9d8')
    pd = ImageDraw.Draw(preview)
    for y in (106, 162, 218):
        pd.rounded_rectangle((56, y, 304, y + 49), radius=16, fill='white', outline='#1a1a1a', width=2)
    pd.rounded_rectangle((153, 276, 263, 321), radius=16, fill='white', outline='#1a1a1a', width=2)
    pd.ellipse((97, 277, 139, 319), fill='white', outline='#1a1a1a', width=2)
    preview.paste('#296065', (0, 0), mask)
    args.preview.parent.mkdir(parents=True, exist_ok=True)
    preview.save(args.preview)
    print(f'Cue bounds={box}, alpha bytes={len(data)}, font SHA256={font_hash}')


if __name__ == '__main__':
    main()
