// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t *ui_Screen6 = NULL;
// event funtions

// build funtions

void ui_Screen6_screen_init(void)
{
ui_Screen6 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color( ui_Screen6, lv_color_hex(0xF5E9D8), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa( ui_Screen6, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_width( ui_Screen6, 40, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_color( ui_Screen6, lv_color_hex(0xD4C4AE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_spread( ui_Screen6, -20, LV_PART_MAIN | LV_STATE_DEFAULT );

lv_obj_set_style_outline_color(ui_Screen6, lv_color_hex(0x000000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_Screen6, 255, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

}

void ui_Screen6_screen_destroy(void)
{
   if (ui_Screen6) lv_obj_del(ui_Screen6);

// NULL screen variables
ui_Screen6= NULL;

}
